Simple Neuron implementation from scratch 

In [13]:
import numpy as np

def relu(output):
    return np.maximum(0,output)

weight = np.random.rand()
bias = np.random.randint(1,10)
input = np.random.randint(1,100)

output = np.dot(weight, input) + bias
print(relu(output))

In [21]:
weights = [[.3,.6,.7],
[.2,.54,.87],
[.96,.23,.55]]

inputs = [[1],
[2],
[3]]

bias = [[2],
[3],
[5]]

output = np.dot(weights, inputs) + bias
print(relu(output))

[[5.6 ]
 [6.89]
 [8.07]]


# Simple 3 Layered Neural Network (Forward Propagation)

In [19]:
import numpy as np
input_original = np.array([[1],[2],[3],[4],[5]]) #(5x1)

#(5x3) matrix: 5 inputs, 3 neurons
weights_layer1 = np.hstack([
   np.array([[.3],[.2],[.5],[.23],[.6]]), #Neuron 1 Weights
   np.array([[.8],[.232],[.9],[.53],[.66]]), #Neuron 2 Weights
   np.array([[.32],[.27],[.655],[.23],[.46]]) #Neuron 3 Weights
]) 

#(3x2) matrix: 3 inputs, 2 neurons
weights_layer2 = np.hstack([
   np.array([[.3],[.2],[.5]]), #Neuron 1 Weights
   np.array([[.8],[.232],[.9]]), #Neuron 2 Weights
]) 

#(2x1), 2 inputs for 1 neuron
weight_final = np.hstack([
   np.array([[0.63],[.75]]) #Final Neuron Weights
])

bias_layer1 = np.array([[3],[1],[5]]) #(3x1)
bias_layer2 = np.array([[1],[2]]) #(2x1)
bias_final = np.array([[7]])

def hidden_layer1(inputs, weights, bias):
   #(1x5)*(5x3) + (1x3), (inputs^T * weights) + bias^T
   output = np.dot(inputs.T, weights) + bias.T #(1x3)
   return np.maximum(0,output)

def hidden_layer2(inputs, weights, bias):
   #(1x3)*(3x2) + (1x3), (inputs^T * weights) + bias^T
   output = np.dot(inputs, weights) + bias.T #(1x3)
   return np.maximum(0,output)

def final_layer(inputs, weights, bias):
   #(2x1)*(1x1) + (1x1)
   output = np.dot(inputs, weights) + bias
   return np.maximum(0,output)
print("Inputs:\n",input_original)
print("Inputs for 1st layer:\n",hidden_layer1(input_original, weights_layer1, bias_layer1))
inputs_2 = np.array(hidden_layer1(input_original, weights_layer1, bias_layer1))
print("Inputs for 2nd layer:\n",hidden_layer2(inputs_2, weights_layer2, bias_layer2))
inputs_final = np.array(hidden_layer2(inputs_2, weights_layer2, bias_layer2)) 
output_final = final_layer(inputs_final, weight_final, bias_final)
print("Final output:\n",output_final.squeeze())

Inputs:
 [[1]
 [2]
 [3]
 [4]
 [5]]
Inputs for 1st layer:
 [[ 9.12  10.384 11.045]]
Inputs for 2nd layer:
 [[11.3353   21.645588]]
Final output:
 30.37543


# 3 Layered Back-Propagation Neural Network

In [44]:
import numpy as np


#        ================== Forward Pass ================== 
''' 
Feed Forward Multi Layer Neural Network:
1. y = mx + c | no = w x i + b | neuron_output = weights x inputs + bias
2. activation_function(neuron_output)
'''

#(3x1)
inputs_original = np.array([[1],[2],[3]])

# Min-Max Input Normalization
input_max = max(inputs_original)
input_min = min(inputs_original)
inputs_normalized = (inputs_original - input_min) / (input_max - input_min)
print("\nInputs Normalized:", inputs_normalized)

# Min-Max Actual Output Normalization
output_min = actual_output
output_max = 2 # Using fixed output range based on training data (not dynamic predictions)
actual_normalized = (actual_output - output_min) / (output_max - output_min)
print("\n Actual Normalized:", actual_normalized,"\n")

#(3x3)
weights_layer1 = np.hstack([
   np.array([[.3],[.34],[.67]]), # Weights for Neuron 1, (3x1)
   np.array([[.2],[.23],[.21]]), # Weights for Neuron 2, (3x1)
   np.array([[.4],[.43],[.11]]) # Weights for Neuron 3, (3x1)
])

#(3x2)
weights_layer2 = np.hstack([
   np.array([[.3],[.34],[.44]]), # Weights for Neuron 1, (3x1)
   np.array([[.2],[.23],[.75]]), # Weights for Neuron 2, (3x1)
])

#(2x1)
weight_final = np.array([[.33],[.66]]) # Weight for final Neuron

bias_layer1 = np.array([[1],[2],[1]]) # Biases for Hidden 1st Layer, (3x1)
bias_layer2 = np.array([[2],[3]]) # Biases for Hidden 2nd Layer, (2x1)
bias_final = np.array([1.1]) # Bias for Final Layer, (1x1)

def hidden_layer1(inputs, weights, bias):
   # (3x1)*(3x3) + (1x3)
   output = np.dot(inputs.T, weights) + bias.T
   return output, np.maximum(0, output)

def hidden_layer2(inputs, weights, bias):
   # (1x3)*(3x2) + (1x2)
   output = np.dot(inputs, weights) + bias.T
   return output, np.maximum(0, output)

def final_layer(inputs, weights, bias):
   # (1x2)*(2x1) + (1x1)
   output = np.dot(inputs, weights) + bias
   return output, output

# 'z' represents raw neuron output without activation function
output_layer_1, z1 = hidden_layer1(inputs_normalized, weights_layer1, bias_layer1) # Forward pass with normalized inputs
output_layer_2, z2 = hidden_layer2(output_layer_1, weights_layer2, bias_layer2)
final_layer, z_final = final_layer(output_layer_2, weight_final, bias_final)
print("================== Forward Pass ==================")
print("1st Layer output:\n", output_layer_1,"\n")
print("2st Layer output:\n", output_layer_2,"\n")
print("Final Layer output:\n", final_layer.squeeze().round(3),'\n')

print("================== Backward Pass ==================")  
'''

==================================== Back Propagation =====================================
1. Loss Function (Mean Squared Error):
   l = 1/2(a - p)^2 | loss = 0.5(actual - predicted)^2

2. Gradients:
Note: Weights, Biases, Final Output are derivated/unpacked to update wrt to gradient/changes/difference between actual & predicted.

   [Final/Output Layer]
      Loss w.r.t Output: (Loss Function Derivative)
         dL/dp = (p - a) | d_loss_output = predicted - actual
      Predicted w.r.t Weight:
         dp/dw = A | d_predicted_weight = neuron_output        ### Note: You can use 'final_output' in place of 'neuron_output' ###
      Loss w.r.t Weight:
         dL/dw = A x (dL/dp) | d_loss_weight = neuron_output x d_loss_output
      Loss w.r.t Bias:
         dL/db = sum(dL/dp) | d_loss_bias = sum(loss_output)

   [Hidden Layer]
      Loss w.r.t  Pre-Activation Neuron Output (Z):
         dL/dZ = dL/dA x dA/dZ = (dL/dp x w).ReLu(Z) | d_loss_raw_neuron_output = (d_loss_output x weight).activation_function(d_raw_neuron_output)
      Loss w.r.t Weight:
         dL/dw = A x (dL/dZ) | d_loss_weight = neuron_output x (d_loss_raw_neuron_output)
      Loss w.r.t Bias:
         dL/db = sum(dL/dZ) | d_loss_bias = sum(d_loss_raw_neuron_output)
   
   [Input Layer]
      Loss w.r.t Pre-Activation Neuron Output (Z):
         dL/dZ = (dL/dZ x w).ReLu(Z) | d_loss_raw_neuron_output = (d_loss_raw_neuron_output x weight).activation_function(d_raw_neuron_output)
      Loss w.r.t Weight:
         dL/dw = i x dL/dZ | d_loss_weight = input x d_loss_raw_neuron_output
      Loss w.r.t Bias:
         dL/db = sum(dL/dZ) | d_loss_bias = sum(d_loss_raw_neuron_output)

   [Update Weights & Biases]
      w = w - (lr x dL/dw) | weight = weight - learning_rate x d_loss_weight
      b = b - (lr x dL/db) | bias = bias - learning_rate x d_loss_weight
'''


def ReLu_derivative(neuron):
   return (neuron > 0).astype(float)
    
def bp_layer_final(A_prev, predicted, actual):
   '''   
   [Final/Output Layer]
      Loss w.r.t Predicted or Output: (Loss Function Derivative)
         dL/dp = (p - a)
      Loss w.r.t Weight:
         dL/dw = A x (dL/dp)
      Loss w.r.t Bias:
         dL/db = sum(dL/dp)
   '''
   '''
    [Final/Output Layer]
      Inputs:
        A_prev: Activation from previous layer (shape: 1xN)
        predicted: Predicted output (shape: 1x1)
        actual: Actual value (scalar)
    '''
   # Loss gradient w.r.t. predicted output (dL/dp) 
   dL_dp = predicted - actual_normalized

   # Clipping gradient between [-1, 1] to avoid gradeint explodes
   dL_dp = np.clip(dL_dp, -1, 1) # Clamping gradients between [-1, 1]

   # Gradient for weights (dL/dw) = A_prev^T @ dL_dp
   dL_dw = A_prev.T @ dL_dp
   
   # Gradient for bias (dL/db) = sum(dL_dp)
   dL_db = np.sum(dL_dp)
   return dL_dw, dL_db

def bp_layer_hidden(A_prev, dL_dz_next, weight_next, z_current):
   '''   
   [Hidden Layer]
      Loss w.r.t  Pre-Activation/Raw Neuron Output (Z):
         dL/dZ = dL/dA x dA/dZ = (dL/dp x w).ReLu(Z)
      Loss w.r.t Weight:
         dL/dw = A x (dL/dZ)
      Loss w.r.t Bias:
         dL/db = sum(dL/dZ)
   '''
   '''
    [Hidden Layer]
      Inputs:
        A_prev: Activation from previous layer (shape: 1xM)
        dL_dz_next: Gradient from the next layer (shape: 1xN)
        weight_next: Weights of the next layer (shape: MxN)
        z_current: Pre-activation of the current layer (shape: 1xM)
    '''
   # Gradient w.r.t. pre-activation (dL/dz_current)
   dL_dz_current = (dL_dz_next @ weight_next.T) * ReLu_derivative(z_current) # (1xR)

   # Gradient for weights (dL/dw) = A_prev^T @ dL_dz_current
   dL_dw = A_prev.T @ dL_dz_current # (RxR)

   # Gradient for bias (dL/db) = sum(dL_dz_current)
   dL_db = np.sum(dL_dz_current)
   return dL_dw, dL_db, dL_dz_current

def bp_layer_input(input_original, dL_dz_next, weight_next, z_current):
   '''   
   [Input Layer]
      Loss w.r.t Pre-Activation Neuron Output (Z):
         dL/dZ = (dL/dZ x w).ReLu(Z)
      Loss w.r.t Weight:
         dL/dw = i x dL/dZ
      Loss w.r.t Bias:
         dL/db = sum(dL/dZ)
   '''
   '''
    [Input Layer]
      Inputs:
        input: Input data (shape: 1xD)
        dL_dz_next: Gradient from the next layer (shape: 1xM)
        weight_next: Weights of the next layer (shape: DxM)
        z_current: Pre-activation of the input layer (shape: 1xD)
    '''
   # Gradient w.r.t. pre-activation (dL/dz_current)
   dL_dz_current = (dL_dz_next @ weight_next.T) * ReLu_derivative(z_current)

   # Gradient for weights (dL/dW) = input.T @ dL_dz_current
   dL_dw = input_original.T @ dL_dz_current

    # Gradient for bias (dL/db) = sum(dL_dz_current)
   dL_db = np.sum(dL_dz_current)
   return dL_dw, dL_db

def update_weights(weight, bias, dL_dw, dL_db, learning_rate):
   '''   
   [Update Weights]
      w = w - (lr x dL/dw)
      b = b - (lr x dL/db)
   '''
   '''Update weights and biases using gradients.'''

   weight = weight - (learning_rate * dL_dw)
   bias = bias - (learning_rate * dL_db)
   return weight, bias


# Implementing back propagation
learning_rate = 0.0001
actual_output = 1

predicted_output = final_layer.round(3).squeeze()
error = actual_output - predicted_output
print("Error(Actual-Predicted): ",error)

# Computing loss gradient (dL/dp)
dL_dp = (final_layer - actual_output) # * ReLu_derivative(z_final) # final_layer is the predicted output

# Storing gradients for final layer weights and biases
dL_dw_final, dL_db_final = bp_layer_final(
   A_prev=output_layer_2, # Activation from previous (hidden) layer
   predicted=final_layer, 
   actual=actual_normalized
)

# Storing gradients for hidden layer2 weights and biases
dL_dw_layer2, dL_db_layer2, dL_dz_layer2 = bp_layer_hidden(
   A_prev=output_layer_1, # Activation from previous layer (hidden layer 1)
   dL_dz_next=dL_dp, # Gradient from final layer
   weight_next=weight_final, # Weights of the next layer (final layer)
   z_current=z2 # Pre-activation of hidden layer 2 (Z2)
)

# Storing gradients for hidden layer1 weights and biases
dL_dw_layer1, dL_db_layer1, dL_dz_layer1 = bp_layer_hidden(
   A_prev=inputs_original.T, # Input data (transposed to match dimensions)
   dL_dz_next=dL_dz_layer2,  # Gradient from hidden layer 2
   weight_next=weights_layer2, # Weights of the next layer (hidden layer 2)
   z_current=z1 # Pre-activation of hidden layer 1 (Z1)
)

# Updating final layer weights and biases
weight_final, bias_final = update_weights(
   weight_final, 
   bias_final,
   dL_dw_final,
   dL_db_final,
   learning_rate
)

# Updating hidden layer2 weights and biases
weights_layer2, bias_layer2 = update_weights(
   weights_layer2,
   bias_layer2,
   dL_dw_layer2,
   dL_db_layer2,
   learning_rate
)

# Updating first hidden layer weights and biases
weights_layer1, bias_layer1 = update_weights(
   weights_layer1,
   bias_layer1,
   dL_dw_layer1,
   dL_db_layer1,
   learning_rate
)

print("\nUpdated Weight & Bias of 1st Hidden Layer:\n", weights_layer1, bias_layer1)
print("\nUpdated Weight & Bias of 2nd Hidden Layer:\n", weights_layer2, bias_layer2)
print("\nUpdated Weight & Bias of Final Layer:\n", weight_final, bias_final)
prediction_denormalized = prediction_normalized * (output_max - output_min) + output_min
print("\n Prediction de-normalized:\n", prediction_denormalized)


Inputs Normalized: [[0. ]
 [0.5]
 [1. ]]

 Actual Normalized: 0.0 

================== Forward Pass ==================
1st Layer output:
 [[1.84  2.325 1.325]] 

2st Layer output:
 [[3.9255 4.8965]] 

Final Layer output:
 5.627 

================== Backward Pass ==================
Error(Actual-Predicted):  -4.627

Updated Weight & Bias of 1st Hidden Layer:
 [[0.29989311 0.19987784 0.39970377]
 [0.33978623 0.22975569 0.42940755]
 [0.66967934 0.20963353 0.10911132]] [[0.99947473]
 [1.99947473]
 [0.99947473]]

Updated Weight & Bias of 2nd Hidden Layer:
 [[0.29971904 0.19943808]
 [0.33964499 0.22928997]
 [0.43979768 0.74959536]] [[1.99954192]
 [2.99954192]]

Updated Weight & Bias of Final Layer:
 [[0.32960745]
 [0.65951035]] [1.0999]


NameError: name 'prediction_normalized' is not defined

# n Epochs Training

In [42]:
epochs_no = int(input("Enter number of Epochs training:"))
learning_rate = 0.0001

for epochs in range(epochs_no):
   # Computing loss gradient (dL/dy_pred)
   dL_dp = (final_layer - actual_normalized)  # * ReLu_derivative(z_final) # final_layer is the predicted output

   # Storing gradients for final layer weights and biases
   dL_dw_final, dL_db_final = bp_layer_final(
      A_prev=output_layer_2, # Activation from previous (hidden) layer
      predicted=final_layer, 
      actual=actual_normalized
   )

   # Storing gradients for hidden layer2 weights and biases
   dL_dw_layer2, dL_db_layer2, dL_dz_layer2 = bp_layer_hidden(
      A_prev=output_layer_1, # Activation from previous layer (hidden layer 1)
      dL_dz_next=dL_dp, # Gradient from final layer
      weight_next=weight_final, # Weights of the next layer (final layer)
      z_current=z2 # Pre-activation of hidden layer 2 (Z2)
   )

   # Storing gradients for hidden layer1 weights and biases
   dL_dw_layer1, dL_db_layer1, dL_dz_layer1 = bp_layer_hidden(
      A_prev=inputs_original.T, # Input data (transposed to match dimensions)
      dL_dz_next=dL_dz_layer2,  # Gradient from hidden layer 2
      weight_next=weights_layer2, # Weights of the next layer (hidden layer 2)
      z_current=z1 # Pre-activation of hidden layer 1 (Z1)
   )

   # Updating final layer weights and biases
   weight_final, bias_final = update_weights(
      weight_final, 
      bias_final,
      dL_dw_final,
      dL_db_final,
      learning_rate
   )

   # Updating hidden layer2 weights and biases
   weights_layer2, bias_layer2 = update_weights(
      weights_layer2,
      bias_layer2,
      dL_dw_layer2,
      dL_db_layer2,
      learning_rate
   )

   # Updating first hidden layer weights and biases
   weights_layer1, bias_layer1 = update_weights(
      weights_layer1,
      bias_layer1,
      dL_dw_layer1,
      dL_db_layer1,
      learning_rate
   )
   print(f"\nUpdated Weight & Bias of Final Layer, Epoch number {epochs+1}:\n", weight_final, bias_final)


Updated Weight & Bias of Final Layer, Epoch number 1:
 [[0.3292149]
 [0.6590207]] [1.0998]

Updated Weight & Bias of Final Layer, Epoch number 2:
 [[0.32882235]
 [0.65853105]] [1.0997]

Updated Weight & Bias of Final Layer, Epoch number 3:
 [[0.3284298]
 [0.6580414]] [1.0996]

Updated Weight & Bias of Final Layer, Epoch number 4:
 [[0.32803725]
 [0.65755175]] [1.0995]

Updated Weight & Bias of Final Layer, Epoch number 5:
 [[0.3276447]
 [0.6570621]] [1.0994]

Updated Weight & Bias of Final Layer, Epoch number 6:
 [[0.32725215]
 [0.65657245]] [1.0993]

Updated Weight & Bias of Final Layer, Epoch number 7:
 [[0.3268596]
 [0.6560828]] [1.0992]

Updated Weight & Bias of Final Layer, Epoch number 8:
 [[0.32646705]
 [0.65559315]] [1.0991]

Updated Weight & Bias of Final Layer, Epoch number 9:
 [[0.3260745]
 [0.6551035]] [1.099]

Updated Weight & Bias of Final Layer, Epoch number 10:
 [[0.32568195]
 [0.65461385]] [1.0989]

Updated Weight & Bias of Final Layer, Epoch number 11:
 [[0.3252894]
